import { useRef, useState } from "react";
import { Copy, Download, Palette, RefreshCw, Save, Search, Upload } from "lucide-react";
import { consoleThemeService } from "../api/themeService";

const COLOR_KEYS=["primaryColor","secondaryColor","accentColor","sidebarBg","headerBg","surfaceColor","borderColor","textPrimary","textSecondary","loginBackground"];
const label=(s)=>s.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());

export default function Themes(){
  const [tenantId,setTenantId]=useState(""); const [sourceId,setSourceId]=useState("");
  const [data,setData]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const importInput=useRef(null);
  const run=async(fn)=>{setBusy(true);setError("");try{setData(await fn());}catch(e){setError(e.response?.data?.message||"Theme operation failed");}finally{setBusy(false);}};
  const change=(key,value)=>setData(d=>({...d,values:{...d.values,[key]:value}}));
  const exportTheme=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${data.tenantCode}-theme.json`;a.click();URL.revokeObjectURL(a.href);};
  const importTheme=async(file)=>{const json=JSON.parse(await file.text());await run(()=>consoleThemeService.update(tenantId,json.values||json));};
  return <div className="space-y-6">
    <header><h1 className="flex items-center gap-2 text-2xl font-bold text-heading"><Palette className="text-accent"/>Theme Management</h1><p className="mt-1 text-sm text-muted">Edit, preview, clone, import, export, and reset isolated tenant branding.</p></header>
    <section className="rounded-2xl border border-border bg-surface p-5 shadow-[var(--sa-card-shadow)]"><label className="text-xs font-semibold uppercase tracking-wide text-muted">Tenant public ID</label><div className="mt-2 flex gap-2"><input className="min-w-0 flex-1 rounded-xl border border-border bg-page px-3 py-2 text-sm text-body outline-none focus:ring-2 focus:ring-focus" value={tenantId} onChange={e=>setTenantId(e.target.value)} placeholder="UUID from Tenants module"/><button disabled={!tenantId||busy} onClick={()=>run(()=>consoleThemeService.get(tenantId))} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Search size={16}/>Load theme</button></div>{error&&<p className="mt-2 text-sm text-hue-red">{error}</p>}</section>
    {data&&<div className="grid gap-6 xl:grid-cols-[1fr_1.1fr]"><section className="space-y-5 rounded-2xl border border-border bg-surface p-5 shadow-[var(--sa-card-shadow)]"><div><h2 className="font-semibold text-heading">{data.tenantName}</h2><p className="font-mono text-xs text-muted">{data.tenantCode}</p></div><div className="grid gap-3 sm:grid-cols-2">{COLOR_KEYS.map(k=><label key={k} className="text-xs font-semibold text-body">{label(k)}<div className="mt-1 flex gap-2"><input type="color" className="h-9 w-11 rounded border border-border" value={data.values[k]} onChange={e=>change(k,e.target.value.toUpperCase())}/><input className="min-w-0 flex-1 rounded-lg border border-border bg-page px-2 font-mono text-xs text-body" value={data.values[k]} onChange={e=>change(k,e.target.value)}/></div></label>)}</div><div className="flex flex-wrap gap-2"><button onClick={()=>run(()=>consoleThemeService.update(tenantId,data.values))} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-sm font-semibold text-white"><Save size={16}/>Save</button><button onClick={()=>run(()=>consoleThemeService.reset(tenantId))} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm text-body"><RefreshCw size={16}/>Reset</button><button onClick={()=>importInput.current.click()} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm text-body"><Upload size={16}/>Import</button><input hidden ref={importInput} type="file" accept="application/json" onChange={e=>e.target.files[0]&&importTheme(e.target.files[0])}/><button onClick={exportTheme} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm text-body"><Download size={16}/>Export</button></div><div className="border-t border-border pt-4"><label className="text-xs font-semibold text-muted">Clone from tenant public ID</label><div className="mt-1 flex gap-2"><input className="min-w-0 flex-1 rounded-xl border border-border bg-page px-3 py-2 text-sm text-body" value={sourceId} onChange={e=>setSourceId(e.target.value)}/><button disabled={!sourceId} onClick={()=>run(()=>consoleThemeService.clone(tenantId,sourceId))} className="inline-flex items-center gap-2 rounded-xl border border-border px-3 text-sm text-body"><Copy size={15}/>Clone</button></div></div></section>
      <section className="overflow-hidden rounded-2xl border border-border bg-surface shadow-[var(--sa-card-shadow)]"><div className="border-b border-border px-5 py-3 text-sm font-semibold text-heading">Live tenant preview</div><div className="grid min-h-[500px] grid-cols-[170px_1fr]" style={{background:data.values.loginBackground,color:data.values.textPrimary,fontFamily:data.values.fontFamily}}><aside className="p-4 text-white" style={{background:data.values.sidebarBg}}><b>{data.tenantName}</b>{["Dashboard","Leads","Bookings","Reports"].map((x,i)=><div key={x} className="mt-4 rounded-lg px-3 py-2 text-sm" style={{background:i===0?data.values.primaryColor:"transparent"}}>{x}</div>)}</aside><div><header className="border-b p-4" style={{background:data.values.headerBg,borderColor:data.values.borderColor}}>Tenant dashboard</header><div className="grid gap-3 p-4 sm:grid-cols-2">{["Leads","Bookings","Revenue","Tasks"].map(x=><div key={x} className="p-4" style={{background:data.values.surfaceColor,border:`1px solid ${data.values.borderColor}`,borderRadius:data.values.borderRadius}}><small style={{color:data.values.textSecondary}}>{x}</small><div className="mt-2 text-xl font-bold">24</div></div>)}</div></div></div></section></div>}
  </div>;
}
